server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: goods-service
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost    
env: dev
branch: master
msg: hello..................33333333333111111111111133

management:
  endpoints:
    web:
      exposure:
        include: "*"
