server:
  port: 8200
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 192.168.160.129
    port: 6379
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
GOODS-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  hystrix:
    enabled: true
#设置hystrix隔离策略中的延迟时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#监控所有服务
management:
  endpoints:
    web:
      exposure:
        include: "*"


